"""empty message

Revision ID: afa69944b485
Revises: 
Create Date: 2018-12-31 09:21:52.181104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa69944b485'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('player_cap', sa.Integer(), nullable=False),
    sa.Column('deck', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('swapping', sa.Boolean(), nullable=True),
    sa.Column('max_idle_time', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hand', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('room')
    op.drop_table('card')
    # ### end Alembic commands ###
